# Generated by Django 5.2.3 on 2025-06-15 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0003_add_user_profiles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activitylog',
            options={'ordering': ['-timestamp'], 'verbose_name_plural': 'Activity Logs'},
        ),
        migrations.AddField(
            model_name='activitylog',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activitylog',
            name='action',
            field=models.CharField(choices=[('LOGIN', 'User login'), ('LOGOUT', 'User logout'), ('CREATE_ANN', 'Announcement created'), ('EDIT_ANN', 'Announcement edited'), ('DELETE_ANN', 'Announcement deleted'), ('UPLOAD_FILE', 'File uploaded'), ('UPDATE_FILE', 'File updated'), ('DELETE_FILE', 'File deleted'), ('ADD_COMMENT', 'Comment added'), ('DELETE_COMMENT', 'Comment deleted'), ('SEARCH', 'Search performed')], max_length=20),
        ),
    ]
